const MESSAGE_ICONS = [
	"announcement icon",
//	"birthday icon",
	"help icon",
	"help circle icon",
	"info icon",
	"info circle icon",
	"warning icon",
	"warning circle icon",
	"warning sign icon"
];

const ITEMSELECTIONS_ICONS = [
	"add circle icon",
	"add square icon",
	"check circle icon",
	"check circle outline icon",
	"check square icon",
	"checkmark box icon",
	"checkmark icon",
	"minus circle icon",
	"minus icon",
	"minus square icon",
	"minus square outline icon",
	"move icon",
	"plus icon",
	"plus square outline icon",
	"radio icon",
	"remove circle icon",
	"remove circle outline icon",
	"remove icon",
	"selected radio icon",
	"toggle off icon",
	"toggle on icon"
];

const POINTERS_ICONS = [
  "angle double down icon",
  "angle double left icon",
  "angle double right icon",
  "angle double up icon",
  "angle down icon",
  "angle left icon",
  "angle right icon",
  "angle up icon",
  "arrow circle down icon",
  "arrow circle left icon",
  "arrow circle outline down icon",
  "arrow circle outline left icon",
  "arrow circle outline right icon",
  "arrow circle outline up icon",
  "arrow circle right icon",
  "arrow circle up icon",
  "arrow down icon",
  "arrow left icon",
  "arrow right icon",
  "arrow up icon",
  "caret down icon",
  "caret left icon",
  "caret right icon",
  "caret up icon",
  "chevron circle down icon",
  "chevron circle left icon",
  "chevron circle right icon",
  "chevron circle up icon",
  "chevron down icon",
  "chevron left icon",
  "chevron right icon",
  "chevron up icon",
];

const RATINGS_ICONS = [
  "empty heart icon",
  "empty star icon",
  "frown icon",
  "heart icon",
  "meh icon",
  "smile icon",
  "star half empty icon",
  "star half icon",
  "star icon",
  "thumbs down icon",
  "thumbs outline down icon",
  "thumbs outline up icon",
  "thumbs up icon",
];

const CURRENCY_ICONS = [
  "dollar icon",
  "euro icon",
  "lira icon",
  "pound icon",
  "ruble icon",
  "rupee icon",
  "won icon",
  "shekel icon",
  "yen icon",
];

const SHAPES_ICONS = [
  "asterisk icon",
  "certificate icon",
  "circle icon",
  "circle notched icon",
  "circle thin icon",
  "crosshairs icon",
  "cube icon",
  "cubes icon",
  "ellipsis horizontal icon",
  "ellipsis vertical icon",
  "quote left icon",
  "quote right icon",
  "spinner icon",
  "square icon",
  "square outline icon",
];

const WEBCONTENT_ICONS = [
  "adjust icon", 
  "add user icon", 
  "add to cart icon", 
  "archive icon", 
  "ban icon", 
  "bookmark icon", 
  "call icon", 
  "call square icon", 
  "cloud download icon", 
  "cloud upload icon", 
  "compress icon", 
  "configure icon", 
  "download icon", 
  "edit icon", 
  "erase icon", 
  "exchange icon", 
  "external share icon", 
  "expand icon", 
  "filter icon", 
  "flag icon", 
  "flag outline icon", 
  "forward mail icon", 
  "hide icon", 
  "in cart icon", 
  "lock icon", 
  "pin icon", 
  "print icon", 
  "random icon", 
  "recycle icon", 
  "refresh icon", 
  "remove bookmark icon", 
  "remove user icon", 
  "repeat icon", 
  "reply all icon", 
  "reply icon", 
  "retweet icon", 
  "send icon", 
  "send outline icon", 
  "share alternate icon", 
  "share alternate square icon", 
  "share icon", 
  "share square icon", 
  "sign in icon", 
  "sign out icon", 
  "theme icon", 
  "translate icon", 
  "undo icon", 
  "unhide icon", 
  "unlock alternate icon", 
  "unlock icon", 
  "upload icon", 
  "wait icon", 
  "wizard icon", 
  "write icon", 
  "write square icon", 
];

export default {
	ALL_ICONS: []
		.concat(MESSAGE_ICONS)
		.concat(ITEMSELECTIONS_ICONS)
		.concat(POINTERS_ICONS)
		.concat(RATINGS_ICONS)
		.concat(CURRENCY_ICONS)
		.concat(SHAPES_ICONS)
    .concat(WEBCONTENT_ICONS)
		,
	MESSAGE_ICONS,
	ITEMSELECTIONS_ICONS,
	POINTERS_ICONS,
	SHAPES_ICONS
}
